### ISSUE TITLE
Logo Dark

### ISSUE THREAD

**Issue by ladyvargas** [cloudinformationmodel/documentation#1]
![image](https://user-images.githubusercontent.com/45071201/125114611-cd1c1380-e0af-11eb-844e-3eed2c6b4f8d.png)

**Comment by jpradocueva** [comment]
See logo files in https://github.com/cloudinformationmodel/documentation/tree/master/static

**Comment by anthonyaveiga** [comment]
solved here: 46b9536dbaf3b9c6968f47c999bc5b5dea79d02f

**Comment by jpradocueva** [comment]
Ok to close from my side.
