### ISSUE TITLE
"Edit this page in GitHub" link is not working

### ISSUE THREAD

**Issue by jpradocueva** [cloudinformationmodel/documentation#10]
I have notice that the link highlighted below, "Edit this page on GitHub" is not working in any of the current Nuxt apps.

![image](https://user-images.githubusercontent.com/3258579/125344108-bc67d980-e30b-11eb-99c6-f335a9f3dffa.png)

**Comment by anthonyaveiga** [comment]
solved in #11

**Comment by jpradocueva** [comment]
@anthonyaveiga Thanks! It is working now.
