### ISSUE TITLE
Menu routes are not working

### ISSUE THREAD

**Issue by ladyvargas** [cloudinformationmodel/documentation#2]
Al momento de dar clic en algún subíndice no direcciona bien. 
![image](https://user-images.githubusercontent.com/45071201/125114701-eb820f00-e0af-11eb-955b-a3e6af4aa191.png)

**Comment by anthonyaveiga** [comment]
Solved in 41304e9d280b9c6621afc39d3278158f8358b863

**Comment by jpradocueva** [comment]
ok to close from my side.
