### ISSUE TITLE
Add light and dark mode

### ISSUE THREAD

**Issue by ladyvargas** [cloudinformationmodel/documentation#3]
![image](https://user-images.githubusercontent.com/45071201/125114893-30a64100-e0b0-11eb-830d-9dcbb7ebf99c.png)

**Comment by jpradocueva** [comment]
I have added 3 different .svg files for the Cloud Information logo, in this folder https://github.com/cloudinformationmodel/documentation/tree/master/static
Please use it and feel free to remove or move the content to another folder.

**Comment by anthonyaveiga** [comment]
Solved here 46b9536dbaf3b9c6968f47c999bc5b5dea79d02f
