### ISSUE TITLE
Remove logo Bluid

### ISSUE THREAD

**Issue by ladyvargas** [cloudinformationmodel/documentation#4]
![image](https://user-images.githubusercontent.com/45071201/125115147-8da1f700-e0b0-11eb-8096-365ffe091926.png)

**Comment by jpradocueva** [comment]
@ladyargas If the logo is the one at the end of the page, as seen in the image below. We agreed that it is ok to keep. If I recall correctly it was challenging to remove. Is that my understanding correct?

![image](https://user-images.githubusercontent.com/3258579/125214123-2fb90f00-e26a-11eb-91d1-1d310ee13125.png)

**Comment by ladyvargas** [comment]
@jpradocueva  Listo, se dejará así entonces!

**Comment by jpradocueva** [comment]
Ok from my side.
