### ISSUE TITLE
Search is not working

### ISSUE THREAD

**Issue by ladyvargas** [cloudinformationmodel/documentation#5]
![image](https://user-images.githubusercontent.com/45071201/125115281-bc1fd200-e0b0-11eb-94d9-0bc4a6e28556.png)

**Comment by anthonyaveiga** [comment]
this also was solved in 41304e9d280b9c6621afc39d3278158f8358b863

**Comment by jpradocueva** [comment]
Assigned also to Lady as she was the creator.
