### ISSUE TITLE
Image URL does not work

### ISSUE THREAD

**Issue by ladyvargas** [cloudinformationmodel/documentation#7]
![image](https://user-images.githubusercontent.com/45071201/125115399-e6718f80-e0b0-11eb-9f5c-dc5f48cdf4c1.png)
![image](https://user-images.githubusercontent.com/45071201/125115449-f4bfab80-e0b0-11eb-911c-aec874fc152b.png)

**Comment by anthonyaveiga** [comment]
solved here 0a6c290f0751067b99ffaca698cec164c45ae277
